name: mpcim
channels:
  - conda-forge
dependencies:
  - altair=5.5.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h753d554_5
  - aws-c-cal=0.9.8=hca30140_0
  - aws-c-common=0.12.5=hc919400_1
  - aws-c-compression=0.3.1=h61d5560_8
  - aws-c-event-stream=0.5.6=hada8b3e_4
  - aws-c-http=0.10.7=h241dc44_1
  - aws-c-io=0.23.2=hcea795d_2
  - aws-c-mqtt=0.13.3=hf26a141_8
  - aws-c-s3=0.8.6=h1e3b5a0_7
  - aws-c-sdkutils=0.2.4=h61d5560_3
  - aws-checksums=0.2.7=h61d5560_4
  - aws-crt-cpp=0.35.0=h44e95eb_2
  - aws-sdk-cpp=1.11.606=hf3ce6b4_6
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.15.0=h10d327b_1
  - azure-storage-common-cpp=12.11.0=h7e4aa5d_1
  - azure-storage-files-datalake-cpp=12.13.0=hb288d13_1
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - brotli-python=1.2.0=py311h69b7e7c_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=6.2.2=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311hd10dc20_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - contourpy=1.3.3=py311h5a5e7c7_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - fonttools=4.60.1=py311ha9b3269_0
  - freetype=2.14.1=hce30654_0
  - gflags=2.2.2=hf9b8971_1005
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glog=0.7.1=heb240a5_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - kiwisolver=1.4.9=py311h26d6576_2
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=21.0.0=h4f7d3e6_11_cpu
  - libarrow-acero=21.0.0=hc317990_11_cpu
  - libarrow-compute=21.0.0=h75845d1_11_cpu
  - libarrow-dataset=21.0.0=hc317990_11_cpu
  - libarrow-substrait=21.0.0=h144af7f_11_cpu
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.5=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=21.0.0=h0ac143b_11_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - libsqlite=3.51.0=h8adb53f_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h4030677_1
  - libutf8proc=2.11.0=hc25f550_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxgboost=3.1.1=cpu_h64a644d_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.5=h4a912ad_2
  - lz4-c=1.10.0=h286801f_1
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib=3.10.8=py311ha1ab1f8_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.11.0=pyhcf101f3_0
  - ncurses=6.5=h5e97a16_3
  - nlohmann_json=3.12.0=h248ca61_1
  - numpy=2.3.4=py311h8685306_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.1=h4fd0076_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hdb8e4fa_1
  - patsy=1.0.2=pyhcf101f3_0
  - pillow=12.0.0=py311h890502c_0
  - pip=25.3=pyh8b19718_0
  - plotly=6.4.0=pyhd8ed1ab_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - protobuf=6.31.1=py311h93f9908_2
  - pthread-stubs=0.4=hd74edd7_1002
  - py-xgboost=3.1.1=cpu_pyh35227d3_0
  - pyarrow=21.0.0=py311ha1ab1f8_1
  - pyarrow-core=21.0.0=py311hf3e52b4_1_cpu
  - pycparser=2.22=pyh29332c3_1
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h18782d2_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311ha9b3269_0
  - qhull=2020.2=h420ef59_5
  - re2=2025.11.05=h64b956e_0
  - readline=8.2=h1d1bf99_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rpds-py=0.28.0=py311h71babbd_2
  - scikit-learn=1.7.2=py311h0f965f6_0
  - scipy=1.16.3=py311h2734c94_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=hada39a4_1
  - statsmodels=0.14.5=py311h09efe57_1
  - streamlit=1.51.0=pyhd8ed1ab_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_3
  - toml=0.10.2=pyhd8ed1ab_2
  - tornado=6.5.2=py311h9408147_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py311h9408147_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - watchdog=6.0.0=py311h9408147_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - xgboost=3.1.1=cpu_pyhb39878e_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - yaml=0.2.5=h925e9cb_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.2.5=h3470cca_0
  - zstandard=0.25.0=py311h5bb9006_1
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/mpcim
