name: mpcim
channels:
  - conda-forge
dependencies:
  - python=3.11
  - streamlit=1.51.0
  - pandas=2.3.3
  - numpy=2.3.4
  - plotly=6.4.0
  - scipy=1.16.3
  - scikit-learn=1.7.2
  - xgboost=3.1.1
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - pip
  - pip:
    # add any pip-only packages here, e.g.:
    # - some-pypi-package==1.2.3
