[theme]
primaryColor = "#1f77b4"
backgroundColor = "#f8f9fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f1724"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[global]
pageTitle = "MPCIM Dashboard"
layout = "wide"
